### PR TITLE
Bunch of little updates

### PR DESCRIPTION
**Pull request by l0ss**
Patch Notes:
Filtered out computer accounts that have a lastlogontimestamp more than 4 months ago.
Fixed a long-standing false-positive in C:\windows\inf
Don't bother trying to read ipc$ and print$ for #OPSECCCCC reasons
Added some discard rules for a few more dirs prone to false positives
Updated the readme!
Updated the sample config!

### CODE REVIEW

**Comment by cmprmsd** [comment]
Great idea reading the `lastlogontimestamp` property. I wonder though, if the value is updated regularly if nobody "interacts" with the computer/server. Imagine servers idling since months that do not have proper patch management and will not be rebooted in months.

I tried finding out about this but that's the only thing I found:
https://social.technet.microsoft.com/Forums/en-US/ff345581-7af5-4536-be29-0e2c125e2fbf/updating-the-lastlogontimestamp-without-loggin-on-in-pcs?forum=winserverDS

**Comment by cmprmsd** [comment]
https://www.sepago.de/blog/the-danger-of-machine-account-password-changes/

It seems it's best practice to disable the regular password rotation, which usually occurs every 30 days. 

I didn't verify it.. Maybe checking for GPOs is sufficient to trigger the timestamp update. :)

**Comment by l0ss** [comment]
We are looking for the computer account’s last logon, not the last time a user logged onto the computer.

**Comment by cmprmsd** [comment]
That's my point. Do computer accounts regularly checkin to the DC when they are not doing anything (but have some old shares) and never get rebooted? 
If they don't then this leads to false positives when the computer runs more than 4 months.

**Comment by l0ss** [comment]
Yeah computer accounts will auth to a DC at least once every 2 hours, because they need to update group policy.

**Pull request merged**
