### PR TITLE
Add interest level parameter

### PR DESCRIPTION
**Pull request by Hackndo**
Add `-b` (interestlevel) parameter so users can filter what interest level will be used & displayed for FileScanner.

* 0 Black, Red, Yellow & Green
* 1 Black, Red & Yellow
* 2 Black, Red
* 3 Black

### CODE REVIEW

**Review by l0ss — COMMENTED** [review]
i need to test this before approving but looks fine in principle

**Comment by l0ss** [comment]
Sorry i took so long to review this properly: The way you've implemented this would work, but it would be slightly more efficient to apply the triage restriction when the classifier rules get built at the very beginning of the run, probably in PrepareClassifiers() in https://github.com/SnaffCon/Snaffler/blob/master/SnaffCore/Config/ClassifierOptions.cs? By removing the low-interest rules from each List<ClassifierRule> we can avoid iterating over them unnecessarily.

I know this sounds like a super tiny efficiency gain but it's the kind of thing that would make a measurable difference in really big environments.

If reimplementing it the way i've described above sounds too annoying, let me know and i'll stick it on the TODO queue (which i'll start working on once Group3r is released)

**Comment by Hackndo** [comment]
I'll try and work on it ASAP :)

**Comment by l0ss** [comment]
Implemented in #51

**Pull request closed without merging**
